"""SHop product jadvalidan kategory_id degan ustunni olib tashladim

Revision ID: e0ecd8555221
Revises: 8a89024f8984
Create Date: 2025-05-26 11:59:34.412835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0ecd8555221'
down_revision: Union[str, None] = '8a89024f8984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('product_ibfk_1', 'product', 'collections', ['category_id'], ['id'])
    # ### end Alembic commands ###
